server:
  port: 8088

spring:
  application:
    name: customer-service

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5435}/customerdb
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: ${INIT_DB:never}  # always / never / embedded
      schema-locations: "classpath:schema.sql"
      data-locations: "classpath:data.sql"

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE
    org.springframework.jdbc.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

jwt:
  privateKeyPath: ${JWT_PRIVATE_KEY_PATH:./config/rsa.pri}
  publicKeyPath: ${JWT_PUBLIC_KEY_PATH:./config/rsa.pub}
admin:
  secretKey: ${ADMIN_SECRET_KEY:your-super-secret-key}
