server:
  port: 8088

spring:
  application:
    name: customer-service

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5435}/customerdb
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: ${INIT_DB:never}  # always / never / embedded
      schema-locations: "classpath:schema.sql"
      data-locations: "classpath:data.sql"

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m

management:
  tracing:
    enabled: false

logging:
  level:
    root: WARN
    com.highvia.customerservice: INFO

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

jwt:
  privateKeyPath: ${JWT_PRIVATE_KEY_PATH:./config/rsa.pri}
  publicKeyPath: ${JWT_PUBLIC_KEY_PATH:./config/rsa.pub}
admin:
  secretKey: ${ADMIN_SECRET_KEY:your-super-secret-key}

---
spring:
  config:
    activate:
      on-profile: prod
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://jaeger.cloudorder.local:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: health,info,metrics
