server:
  port: 8089

spring:
  application:
    name: product-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: product-query-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


amazon:
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:http://localhost:8003}
    region: ${AWS_REGION:us-west-1}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  publicKeyPath: ${JWT_PUBLIC_KEY_PATH:./config/rsa.pub}

---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
