server:
  port: 8090

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5438}/${DB_NAME:order_write_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# OpenFeign logging
logging:
  level:
    com.highvia.orderservice.client.ProductClient: INFO

jwt:
  publicKeyPath: config/rsa.pub

services:
  cart:
    url: ${CART_SERVICE_URL:http://localhost:8083}
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8089}

---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false