server:
  port: 8084

spring:
  application:
    name: seckill-service

  #Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Eureka

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# JWT

jwt:
  publicKeyPath: ${JWT_PUBLIC_KEY_PATH:./config/rsa.pub}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# Logging

logging:
  level:
    com.highvia.seckillservice: DEBUG
    org.springframework.data.redis: INFO

services:
  product:
    url: ${PRODUCT_SERVICE_URL:http://localhost:8089}
