package com.highvia.productservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Products")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductEntity {
    @DynamoDBHashKey(attributeName = "productId")
    //@DynamoDBAutoGeneratedKey
    private Long productId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private Double price;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private Integer stock;

    @DynamoDBVersionAttribute
    private Long version;
}
